apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  namespace: external-systems
  description: Petstore
spec:
  type: service
  lifecycle: experimental
  owner: group:arquitectura_tecnologia
  providesApis:
    - petstore
    - internal/streetlights
    - hello-world